on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'oscal'
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
name: Process Content Artifacts
env:
  HOME_REPO: usnistgov/OSCAL
  # With the default GEN_CONTENT_DIR, the resulting catalogs, profiles, and
  # other example content will end up in the build/generated directory. For
  # checking in finalized content, it goes into build/.., the top-level
  # directory of this project.
  GEN_CONTENT_DIR: ..
jobs:
  validate-and-publish-content:
    name: Check, Convert and Validate Content
    runs-on: ubuntu-20.04
    steps:
      # use this if checkout needs to be authenticated
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        if: github.repository == env.HOME_REPO && github.ref == 'refs/heads/main'
        with:
          submodules: recursive
          token: ${{ secrets.COMMIT_TOKEN }}
      # use this if checkout is anonymous
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        if: github.repository != env.HOME_REPO || github.ref != 'refs/heads/main'
        with:
          submodules: recursive
      - name: Copy and convert content
        run: |
          make -C build all GEN_CONTENT_DIR=${{env.GEN_CONTENT_DIR}}
        id: copy-convert
      - name: Zip Artifacts for Upload
        if: always()
        run: |
          zip ${{ runner.temp }}/generated-content.zip -r .
        working-directory: ${{ github.workspace }}
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        if: always()
        with:
          name: generated-content
          path: |
            ${{ runner.temp }}/generated-content.zip
          retention-days: 5
      - name: Publish Artifacts
        # only do this on main
        if: github.repository == env.HOME_REPO && github.ref == 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a
        with:
          push_options: --force
          commit_message: Publishing auto-converted artifacts
          commit_user_name: OSCAL GitHub Actions Bot
          commit_user_email: oscal@nist.gov
          commit_author: OSCAL GitHub Actions Bot <oscal@nist.gov>
